from pydantic import BaseModel
from typing import List, Optional
from datetime import date
from enum import Enum

# --- Enums (Rules) ---
# We repeat Enums here so API knows what values are allowed in JSON
class MatchResult(str, Enum):
    TEAM_A = "TEAM_A"
    TEAM_B = "TEAM_B"
    DRAW = "DRAW"

# --- Player schemas ---

# What is common when reading or writing
class PlayerBase(BaseModel):
    name: str

# Create: What we need to create a new player (just the name)
class PlayerCreate(PlayerBase):
    pass

# Response: What we return to the user (includes the ID generated by DB)
class Player(PlayerBase):
    id: int

    class Config:
        from_attributes = True # Allows pydantic to read sqlalchemy tools

# --- Match Schemas ---

class MatchBase(BaseModel):
    date: date
    result: MatchResult

class MatchCreate(MatchBase):
    # When creating a match, we receive a list of player ids for each team
    team_a_players: List[int]
    team_b_players: List[int]

class Match(MatchBase):
    id: int
    # To add nested player details here

    class Config:
        from_attributes = True

